export type PhaseRoadmapStatus =
  | "shipped"
  | "foundation"
  | "needs_data"
  | "external_review";

export type PhaseRoadmapItem = {
  phase: number;
  title: string;
  summary: string;
  category: string;
  status: PhaseRoadmapStatus;
  guardrail: string;
  artifact: string;
};

export const PHASE_ROADMAP_STATUS_LABELS: Record<PhaseRoadmapStatus, string> = {
  shipped: "実装済み",
  foundation: "土台整備済み",
  needs_data: "データ蓄積待ち",
  external_review: "外部確認待ち",
};

export const PHASE_ROADMAP: readonly PhaseRoadmapItem[] = [
  {
    phase: 13,
    title: "初期データ投入・審査ワークフロー強化",
    summary: "初期データ候補を管理者限定の審査DBで扱い、公開前確認を分離します。",
    category: "審査",
    status: "shipped",
    guardrail: "公開承認とは分け、候補は非公開で扱う。",
    artifact: "PHASE_23_REVIEW_WORKFLOW_PLAN.md",
  },
  {
    phase: 14,
    title: "データ品質・重複確認",
    summary: "同一住所・同一建物の候補を確認しやすくし、同一性は断定しません。",
    category: "品質",
    status: "shipped",
    guardrail: "同一運営や同一店舗とは断定しない。",
    artifact: "DATA_QUALITY_SOP.md",
  },
  {
    phase: 15,
    title: "公開情報ページ強化",
    summary: "エリア別、種別別、確認リスト別の情報導線を増やします。",
    category: "公開UI",
    status: "shipped",
    guardrail: "承認済み情報と一般的な確認項目を分ける。",
    artifact: "/areas, /topics, /checklists",
  },
  {
    phase: 16,
    title: "投稿獲得導線強化",
    summary: "情報提供、SNS共有、相談導線から投稿フォームへ自然に導きます。",
    category: "成長",
    status: "shipped",
    guardrail: "煽り文面や断定表現で投稿を集めない。",
    artifact: "/contribute, /social",
  },
  {
    phase: 17,
    title: "異議申立て・削除依頼フロー強化",
    summary: "店舗側や関係者からの確認依頼を受け、再審査や非公開化に回せます。",
    category: "法務",
    status: "shipped",
    guardrail: "異議申立て中は確認を優先する。",
    artifact: "/objection, /admin/objections",
  },
  {
    phase: 18,
    title: "収益化準備",
    summary: "広告、スポンサー、掲載独立性の方針を分けて準備します。",
    category: "収益化",
    status: "shipped",
    guardrail: "広告主が表示順位や注意情報へ影響しない。",
    artifact: "/monetization-policy, /sponsor",
  },
  {
    phase: 19,
    title: "運用監視・バックアップ",
    summary: "公開前後のチェック、監視、バックアップ手順を整備します。",
    category: "運用",
    status: "shipped",
    guardrail: "障害時も非公開情報を復旧ログに出さない。",
    artifact: "BACKUP_AND_MONITORING_RUNBOOK.md",
  },
  {
    phase: 20,
    title: "MVP公開後改善",
    summary: "投稿数、検索流入、審査工数を見ながら改善します。",
    category: "運用",
    status: "shipped",
    guardrail: "数値改善より公開安全性を優先する。",
    artifact: "PHASE_13_20_ROADMAP.md",
  },
  {
    phase: 21,
    title: "初期データ投入とSEO土台",
    summary: "公開情報を増やす前に出典、確認日、独自要約の型を整えます。",
    category: "情報蓄積",
    status: "shipped",
    guardrail: "外部本文や画像を転載しない。",
    artifact: "PHASE_21_DATA_INTAKE_PLAN.md",
  },
  {
    phase: 22,
    title: "審査キューから非公開投入までの短縮",
    summary: "管理者限定の候補登録で、公開前の確認作業を短縮します。",
    category: "審査",
    status: "shipped",
    guardrail: "非公開投入は公開承認ではない。",
    artifact: "PHASE_22_REVIEW_IMPORT_PLAN.md",
  },
  {
    phase: 23,
    title: "候補審査DB",
    summary: "出典確認、要約確認、建物確認、法務確認を候補単位で記録します。",
    category: "審査",
    status: "shipped",
    guardrail: "RLSとService Roleの境界を維持する。",
    artifact: "supabase/migrations/0010_initial_data_review_workflow.sql",
  },
  {
    phase: 24,
    title: "掲載エリア拡大",
    summary: "12エリアに拡大しつつ、公開条件は変えません。",
    category: "エリア",
    status: "shipped",
    guardrail: "エリア拡大は未承認投稿の公開ではない。",
    artifact: "supabase/migrations/0011_area_expansion.sql",
  },
  {
    phase: 25,
    title: "エリア別コンテンツ増強",
    summary: "各エリアの確認リスト、記録保存、情報提供導線を厚くします。",
    category: "公開UI",
    status: "shipped",
    guardrail: "一般的確認項目と個別報告を混同しない。",
    artifact: "PHASE_25_CONTENT_DEPTH_PLAN.md",
  },
  {
    phase: 26,
    title: "エリア運用管理",
    summary: "エリア別ソース、投稿導線、建物確認、コンテンツ増強を管理します。",
    category: "運用",
    status: "shipped",
    guardrail: "運用キューは公開判断ではない。",
    artifact: "/admin/area-ops",
  },
  {
    phase: 27,
    title: "公式ソース安全候補",
    summary: "公式ソース由来のエリア単位候補をCSVと管理画面で扱います。",
    category: "情報蓄積",
    status: "shipped",
    guardrail: "個別店舗の根拠なし公開に使わない。",
    artifact: "OFFICIAL_SOURCE_SEED_CANDIDATES.csv",
  },
  {
    phase: 28,
    title: "本番DB審査ワークフロー適用",
    summary: "本番DBに審査ワークフローを適用し、公式候補12件を非公開登録しました。",
    category: "本番運用",
    status: "shipped",
    guardrail: "12件は公開投稿ではなく、needs_review / Hiddenで保持する。",
    artifact: "PHASE_28_PRODUCTION_SEED_RUN.md",
  },
  {
    phase: 29,
    title: "透明性センター",
    summary: "公開する情報、公開しない情報、審査、異議申立て、収益化独立性をまとめます。",
    category: "信頼",
    status: "foundation",
    guardrail: "非公開列名や証拠保存先を公開UIへ出さない。",
    artifact: "/trust",
  },
  {
    phase: 30,
    title: "公式候補の公開反映ルール",
    summary: "公式候補をエリアページや確認リストの改善に使い、個別店舗化しません。",
    category: "情報蓄積",
    status: "foundation",
    guardrail: "公式ソース候補を承認済み報告として扱わない。",
    artifact: "PHASE_29_50_EXPANSION_ROADMAP.md",
  },
  {
    phase: 31,
    title: "エリア別公式確認先の強化",
    summary: "公式確認先、相談導線、記録保存をエリア別に見つけやすくします。",
    category: "公開UI",
    status: "foundation",
    guardrail: "行政資料の本文や店舗一覧を転載しない。",
    artifact: "/sources, /coverage",
  },
  {
    phase: 32,
    title: "投稿品質スコアの運用設計",
    summary: "投稿の具体性、証拠有無、個人情報リスクを審査観点として整理します。",
    category: "審査",
    status: "foundation",
    guardrail: "スコアは公開評価ではなく管理者の確認補助に限定する。",
    artifact: "PHASE_29_50_EXECUTION_MATRIX.csv",
  },
  {
    phase: 33,
    title: "証拠ファイル確認SOPの厚み",
    summary: "EXIF、顔、個人情報、レシート情報の確認観点を運用に残します。",
    category: "セキュリティ",
    status: "foundation",
    guardrail: "証拠画像と直接URLは一般公開しない。",
    artifact: "OPERATIONS_SOP.md",
  },
  {
    phase: 34,
    title: "異議申立て再審査基準",
    summary: "掲載内容、反論、削除依頼、非公開化の判断を分けます。",
    category: "法務",
    status: "foundation",
    guardrail: "公開維持より再確認を優先する。",
    artifact: "LEGAL_REVIEW_NOTES.md",
  },
  {
    phase: 35,
    title: "検索流入の安全強化",
    summary: "エリア、種別、確認リストを軸に、煽らず検索されるページを増やします。",
    category: "SEO",
    status: "foundation",
    guardrail: "断定、攻撃、ランキング表現を避ける。",
    artifact: "/topics, /areas/[slug]/topics/[topicSlug]",
  },
  {
    phase: 36,
    title: "ゼロ件ページの価値向上",
    summary: "公開報告がないエリアでも確認項目、相談先、情報提供導線を出します。",
    category: "公開UI",
    status: "foundation",
    guardrail: "報告がないことを安全と表現しない。",
    artifact: "/coverage",
  },
  {
    phase: 37,
    title: "SNS運用テンプレート拡張",
    summary: "自然拡散用の投稿案と確認フローを整えます。",
    category: "SNS",
    status: "foundation",
    guardrail: "店舗や個人への攻撃を誘発しない。",
    artifact: "SNS_OPERATIONS_SOP.md",
  },
  {
    phase: 38,
    title: "スポンサー審査基準",
    summary: "掲載独立性、広告表示、問い合わせ対応を分けて運用します。",
    category: "収益化",
    status: "foundation",
    guardrail: "スポンサーの有無で注意情報を変えない。",
    artifact: "/sponsor, /monetization-policy",
  },
  {
    phase: 39,
    title: "無料枠計測",
    summary: "無料枠で見られる公開導線、投稿導線、管理工数を追います。",
    category: "計測",
    status: "foundation",
    guardrail: "個人情報や証拠情報を計測イベントへ入れない。",
    artifact: "FREE_TIER_GROWTH_PLAN.md",
  },
  {
    phase: 40,
    title: "監視と復旧訓練",
    summary: "健康確認、公開HTMLスキャン、バックアップ手順を定期運用にします。",
    category: "運用",
    status: "foundation",
    guardrail: "ログに秘密鍵や非公開情報を残さない。",
    artifact: "BACKUP_AND_MONITORING_RUNBOOK.md",
  },
  {
    phase: 41,
    title: "情報鮮度バッジ",
    summary: "出典確認日、再確認待ち、リンク確認の状態を管理者が追えるようにします。",
    category: "情報品質",
    status: "needs_data",
    guardrail: "古い情報を現在の事実として断定しない。",
    artifact: "/admin/area-ops",
  },
  {
    phase: 42,
    title: "相談先連携の整理",
    summary: "警察相談、消費生活相談、カード会社相談の導線を分かりやすく保ちます。",
    category: "相談導線",
    status: "foundation",
    guardrail: "法的助言ではなく一般的な相談先案内に留める。",
    artifact: "/support",
  },
  {
    phase: 43,
    title: "法務レビューゲート",
    summary: "公開前に断定表現、営業妨害リスク、個人情報を確認します。",
    category: "法務",
    status: "external_review",
    guardrail: "本番公開文面は人間レビューを必須にする。",
    artifact: "LEGAL_REVIEW_NOTES.md",
  },
  {
    phase: 44,
    title: "管理者処理速度の見える化",
    summary: "審査待ち、差し戻し、異議申立て、証拠確認の滞留を見ます。",
    category: "管理",
    status: "needs_data",
    guardrail: "処理速度のために公開審査を省略しない。",
    artifact: "/admin",
  },
  {
    phase: 45,
    title: "公開API方針",
    summary: "公開APIは急がず、公開ビューだけを対象にする方針を固定します。",
    category: "セキュリティ",
    status: "foundation",
    guardrail: "非公開投稿、メール、証拠、管理メモをAPI化しない。",
    artifact: "/trust",
  },
  {
    phase: 46,
    title: "アクセシビリティとスマホUX",
    summary: "主要ページで横スクロールを避け、フォームと地図をスマホで扱いやすくします。",
    category: "UX",
    status: "foundation",
    guardrail: "フォーム入力中に重要注意文を隠さない。",
    artifact: "tests/smoke.spec.ts",
  },
  {
    phase: 47,
    title: "公開前自動スキャン",
    summary: "禁止表現、非公開情報、Service Role混入を公開前に確認します。",
    category: "テスト",
    status: "shipped",
    guardrail: "スキャンOKでも人間審査を省かない。",
    artifact: "tests/release-artifacts.spec.ts",
  },
  {
    phase: 48,
    title: "初期データ追加の定例化",
    summary: "公式ソース、報道、自社確認メモを週次で候補化します。",
    category: "情報蓄積",
    status: "needs_data",
    guardrail: "Google口コミ、SNS、ニュース本文を転載しない。",
    artifact: "DATA_COLLECTION_PLAYBOOK.md",
  },
  {
    phase: 49,
    title: "収益化実験の開始条件",
    summary: "AdSense、スポンサー、寄付導線は安全条件を満たした後に始めます。",
    category: "収益化",
    status: "external_review",
    guardrail: "広告が審査判断や掲載順位に影響しない。",
    artifact: "ADSENSE_SETUP_GUIDE.md",
  },
  {
    phase: 50,
    title: "リリースガバナンス",
    summary: "DB、RLS、公開UI、法務、運用、収益化の最終判断基準を固定します。",
    category: "本番運用",
    status: "foundation",
    guardrail: "危険条件が残る場合は公開拡大しない。",
    artifact: "PHASE_29_50_EXPANSION_ROADMAP.md",
  },
] as const;

export function getPhaseRoadmapByRange(start: number, end: number) {
  return PHASE_ROADMAP.filter((item) => item.phase >= start && item.phase <= end);
}

export function getPhaseRoadmapMetrics() {
  return {
    total: PHASE_ROADMAP.length,
    shipped: PHASE_ROADMAP.filter((item) => item.status === "shipped").length,
    foundation: PHASE_ROADMAP.filter((item) => item.status === "foundation").length,
    needsData: PHASE_ROADMAP.filter((item) => item.status === "needs_data").length,
    externalReview: PHASE_ROADMAP.filter((item) => item.status === "external_review")
      .length,
  };
}

